def options(opt):
        print("mcal options!")

def configure(cnf):
        print("mcal configure!")

def build(bld):
        print("mcal build!")
        bld(
                #features='c cxx cxxstlib',
                #features='c cxxstlib',
                features='c cshlib',
                source="src/gpio.c src/led.c",
                target="mcal"
        )
        