#!/usr/bin/env python
# encoding: utf-8
# Richard Andrysek, 2024
# RENU Eletronics 2024 Copyright

def options(opt):
        print("mcal options!")


def configure(cnf):
        print("mcal configure!")


def build(bld):
        print("mcal build!")
        bld(
                #features='c cxx cxxstlib',
                #features='c cxxstlib',
                features='c cshlib',
                source="src/gpio.c src/led.c",
                target="mcal"
        )
        