#!/usr/bin/env python
# encoding: utf-8
# Richard Andrysek, 2024
# RENU Eletronics 2024 Copyright

def options(opt):
        print("app options!")


def configure(cnf):
        print("app configure!")


def build(bld):
        print("app build!")
        bld(
                features='c cxx cxxprogram',
                source=["src/main.c"],
                target="helloworld", 
                use=["mcal"]
        )
        